def query(time_diff,timestamp,db,company_name,site,max_ts):
    sql = """
        SELECT
						'{4}'														AS [site]
						,[Entry No_]
							  ,[Entry Type]
							  ,[Customer Item No_]
							  ,[Item No_]
							  ,[Carrier No_]
                              ,NULL AS [Open]
							  ,[Location No_]
							  ,[Source Type]
							  ,[Source No_]
							  ,CAST([Posting Date] AS DATE)  [Posting Date]
							  ,[Quantity]
							  ,[Unit of Measure Code]
							  ,[Qty_ per Unit of Measure]
							  ,[Quantity (Base)]
							  ,[Source Entry Type]
							  ,[Storage Charge No_]
                              , NULL AS [Parent Carrier No_]
							  ,[Description]
							  ,[Batch No_]
							  ,[Item Condition]
							  ,[Quantity Carrier]
							  ,[Dossier No_]
							  ,[Source Code]
							  ,[Building Code]
							  ,[Unit of Measure Code (Base)]
							  ,[Length]
							  ,[Width]
							  ,[Height]
							  ,[Cubage]
							  ,[Global Dimension 1 Code]
							  ,[Global Dimension 2 Code]
							  ,[Specification Set ID]
							  ,[Carrier Type Code]
							  ,[External Customer Item No_]
							  ,[Reason Code]
							  ,CAST([Expiration Date] AS DATE) [Expiration Date]
							  ,CAST([Production Date] AS DATE) [Production Date]
							  ,CAST([Receipt Date] AS DATE) [Receipt Date]
							  ,[External Carrier No_]
							  ,[Production Period]
							  ,CAST([Freezing Date] AS DATE) [Freezing Date]
							  ,[Unit Cost (LCY)]
							  ,[Total Cost (LCY)]
							  ,[Document Type]
							  ,[Document No_]
							  ,[Document Line No_]
							  ,CASE WHEN [Document Date] LIKE '1753%' THEN '1753-01-01' ELSE CAST([Document Date] AS DATE) END [Document Date]
							  ,[Process Line No_]
							  ,[Process Type]
							  ,[Process Type Line No_]
							  ,[Process Line Group]
							  ,[Net Weight]
							  ,[Gross Weight]
							  ,[Package Set ID]
							  ,[Weight Registration]
							  ,[Feature Recognition]
							  ,[Zone Code]
							  ,[Zone Type]
							  ,[External Batch No_]
							  ,[Taric Code]
							  ,[Customs Code]
							  ,[Tariff No_]
							  ,[Customs Value]
							  ,[Customs Value per]
							  ,[Customs Currency Code]
							  ,[Entrepot Storage]
							  ,[Private Storage]
							  ,[Cross-docking]
							  ,[Production Code]
							  ,[Carrier Set ID]
							  ,[Address No_]
							  ,[Dimension Set ID]
							  ,[User ID]
    						  ,DATEADD(mi,{0},[Created Date_Time]) [Created Date_Time]
							  ,DATEADD(mi,{0},[Modified Date_Time]) [Modified Date_Time]
							  ,[System-Created Entry]
							  ,[Related Entry No_]
							  ,[Undo Posting]
							  ,[Attribute 01]
							  ,[Attribute 02]
							  ,[Attribute 03]
							  ,[Attribute 04]
							  ,[Attribute 05]
							  ,[Attribute 06]
							  ,[Attribute 07]
							  ,[Attribute 08]
							  ,[Attribute 09]
							  ,[Attribute 10]
							  ,[Item Category Code]
							  ,[Product Group Code]
  							  ,[Cycle Counting Task Entry No_]
							  ,[Receipt Carrier No_]
							  ,CAST(ile.[timestamp] AS BIGINT)													AS [ts_boltrics]
							  ,CAST('{1}' AS DATETIME)												AS [ts_creation]
						FROM  [{2}].dbo.[{3}$WMS Item Ledger Entry] ile where [Entry No_] > 0
						AND [Document No_] NOT LIKE 'CONVERS%'
					    AND CONVERT(BIGINT,ile.[timestamp]) > {5}""".format(time_diff,timestamp,db,company_name,site,max_ts)


    return sql
